#!/usr/bin/env python3
"""
Seed the rooms.coords column with pixel positions derived from map_with_beds.png.

The image is 530x395 px.  coords format: "x,y,w,h" (left, top, width, height)
relative to the top-left of the image.

Run inside the VenerableWebsite worktree:
  python3 database/seed_room_coords.py <db_url>

Or pass no arguments to print the SQL only.
"""

import sys

# ---------------------------------------------------------------------------
# Coordinate mapping  (room_number: "x,y,w,h")
# Measured from map_with_beds.png (530x395).
# These are approximate — fine-tune visually against the overlay.
# ---------------------------------------------------------------------------
COORDS = {
    # ---- Alley 1 (pink, left block) ----
    # Right-side column (top→bottom): 138, 136, 134, 132, 130
    138: "67,2,70,27",
    136: "67,30,70,27",
    134: "67,58,70,27",
    132: "67,86,70,27",
    130: "67,114,70,27",
    # Left-side column: 133, 131(vacant — coords kept for reference)
    133: "2,86,48,27",
    131: "2,114,48,27",   # permanently vacant; tile not rendered

    # ---- Alley 2 (yellow, left block lower) ----
    # Left column
    127: "2,197,62,27",
    125: "2,225,62,27",
    # Right-side row (horizontal)
    123: "87,197,40,27",
    121: "128,197,40,27",
    119: "169,197,40,27",
    # Extension into center section (Alley-2 rooms)
    114: "246,160,66,27",
    112: "246,188,66,27",   # forced frosh; tile shown red

    # ---- Alley 3 (teal, center block) ----
    # Right-side column (top→bottom): 110, 108, 106, 104
    110: "246,216,66,27",
    108: "246,244,66,27",
    106: "246,272,66,27",
    104: "246,300,66,27",
    # Left-side column: 105, 103, 101
    105: "200,272,45,27",
    103: "200,300,45,27",
    101: "200,328,45,27",

    # ---- Alley 4 (purple, right block left column) ----
    # Top→bottom: 244, 242, 240, 238, 236, 234
    244: "400,2,62,27",
    242: "400,30,62,27",
    240: "400,58,62,27",
    238: "400,86,62,27",
    236: "400,114,62,27",
    234: "400,142,62,27",

    # ---- Alley 5 (green, right block middle area) ----
    # Left sub-corridor (top→bottom): 229, 227
    229: "355,197,52,27",
    227: "355,225,52,27",
    # Right sub-corridor (row, then column): 225, 223, 221
    225: "410,254,42,27",
    223: "410,226,42,27",
    221: "410,197,42,27",
    # Upper row connecting to Alley 6: 220, 218, 216
    220: "434,197,40,27",
    218: "475,197,40,27",
    216: "475,225,40,27",

    # ---- Alley 6 (grey, right block far right) ----
    # Upper column (top→bottom): 214, 212, 210, 208, 206, 204
    214: "496,197,32,27",
    212: "496,225,32,27",
    210: "496,253,32,27",
    208: "496,281,32,27",
    206: "496,309,32,27",
    204: "496,337,32,27",
    # Lower-left sub-corridor: 205, 203, 201
    205: "462,281,32,27",
    203: "462,309,32,27",
    201: "462,337,32,27",
}

# ---------------------------------------------------------------------------

def make_sql():
    lines = []
    lines.append("-- Seed rooms.coords — generated by seed_room_coords.py")
    lines.append("-- Run inside a transaction so you can ROLLBACK if needed.")
    lines.append("BEGIN;")
    for room_number, coords in sorted(COORDS.items()):
        lines.append(
            "UPDATE rooms SET coords = '{}' WHERE room_number = {};".format(
                coords, room_number))
    lines.append("COMMIT;")
    return "\n".join(lines)


if __name__ == "__main__":
    sql = make_sql()
    if len(sys.argv) < 2:
        print(sql)
        sys.exit(0)

    try:
        import sqlalchemy
        engine = sqlalchemy.create_engine(sys.argv[1])
        with engine.begin() as conn:
            for room_number, coords in COORDS.items():
                conn.execute(
                    sqlalchemy.text(
                        "UPDATE rooms SET coords = :c WHERE room_number = :r"),
                    c=coords, r=room_number)
        print("Done — updated {} rooms.".format(len(COORDS)))
    except Exception as e:
        print("Error:", e)
        sys.exit(1)
